
######################################################################
# Automatically generated by qmake (3.0) ?? 11? 30 09:55:49 2017
######################################################################

TEMPLATE = subdirs

SUBDIRS += \
           src \
           delete-files \
           file-shredder \
           network-test \
           service-manager \
           startup-apps
