######################################################################
# Automatically generated by qmake (3.0) ?? 11? 16 14:46:22 2019
######################################################################

QT += core gui network

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = sysbro-network-test
INCLUDEPATH += .

CONFIG += c++11 link_pkgconfig
PKGCONFIG += dtkwidget

# Input
HEADERS += homepage.h mainwindow.h networkmanager.h
SOURCES += homepage.cpp main.cpp mainwindow.cpp networkmanager.cpp
RESOURCES += resoureces.qrc

PREFIX = /usr
BINDIR = $$PREFIX/bin

target.path = $$BINDIR

INSTALLS += target
