######################################################################
# Automatically generated by qmake (3.0) ?? 11? 16 14:43:31 2019
######################################################################

QT += core

TEMPLATE = app
TARGET = sysbro-delete-files
INCLUDEPATH += .

CONFIG += c++11

# Input
SOURCES += main.cpp

PREFIX = /usr
BINDIR = $$PREFIX/bin

target.path = $$BINDIR

INSTALLS += target
