######################################################################
# Automatically generated by qmake (3.0) ?? 11? 16 14:47:37 2019
######################################################################

QT += core

TEMPLATE = app
TARGET = sysbro-service-mgr
INCLUDEPATH += .

# Input
SOURCES += main.cpp

PREFIX = /usr
BINDIR = $$PREFIX/bin

target.path = $$BINDIR

INSTALLS += target
